import React from 'react';

const Contamination = () => {
  return (
    <div className="grid grid-cols-3 gap-4 p-4 h-screen bg-blue-200 p-8 ">
<div className="bg-white rounded-lg shadow-lg p-4  col-span-2 row-span-2 overflow-y-scroll">
  <h2 className="text-[35px] text-gray-900 font-bold mb-4">Articles</h2>
  <div className="bg-gray-100 p-4 rounded-lg my-2 ">
    <h3 className="text-md font-bold text-gray-800 mb-2">What Is Water Pollution?</h3>
    <p className="text-gray-700 ">
Water pollution occurs when harmful substances—often chemicals or microorganisms—contaminate a stream, river, lake, ocean, aquifer, or other body of water, degrading water quality and rendering it toxic to humans or the environment.

This widespread problem of water pollution is jeopardizing our health. Unsafe water kills more people each year than war and all other forms of violence combined. Meanwhile, our drinkable water sources are finite: Less than 1 percent of the earth’s freshwater is actually accessible to us. Without action, the challenges will only increase by 2050, when global demand for freshwater is expected to be one-third greater than it is now.
    </p>
  </div>
  <div className="bg-gray-100 p-4 rounded-lg my-2 ">
    <h3 className="text-md font-bold text-gray-800 mb-2">article 2 for contamination of water</h3>
    <p className="text-gray-700 ">

    Not only is the agricultural sector the biggest consumer of global freshwater resources, with farming and livestock production using about 70 percent of the earth’s surface water supplies, but it’s also a serious water polluter. Around the world, agriculture is the leading cause of water degradation. In the United States, agricultural pollution is the top source of contamination in rivers and streams, the second-biggest source in wetlands, and the third main source in lakes. It’s also a major contributor of contamination to estuaries and groundwater. Every time it rains, fertilizers, pesticides, and animal waste from farms and livestock operations wash nutrients and pathogens—such bacteria and viruses—into our waterways.

    </p>
  </div>
  <div className="bg-gray-100 p-4 rounded-lg my-2 ">
    <h3 className="text-md font-bold text-gray-800 mb-2">article 3</h3>
    <p className="text-gray-700 ">

    More than 80 percent of the world’s wastewater flows back into the environment without being treated or reused, according to the United Nations; in some least-developed countries, the figure tops 95 percent. In the United States, wastewater treatment facilities process about 34 billion gallons of wastewater per day. These facilities reduce the amount of pollutants such as pathogens, phosphorus, and nitrogen in sewage, as well as heavy metals and toxic chemicals in industrial waste, before discharging the treated waters back into waterways. That’s when all goes well. But according to EPA estimates, our nation’s aging and easily overwhelmed sewage treatment systems also release more than 850 billion gallons of untreated wastewater each year.

    </p>
  </div>
  <div className="bg-gray-100 p-4 rounded-lg my-2 ">
    <h3 className="text-md font-bold text-gray-800 mb-2">article 4</h3>
    <p className="text-gray-700 ">

    Big spills may dominate headlines, but consumers account for the vast majority of oil pollution in our seas, including oil and gasoline that drips from millions of cars and trucks every day. Moreover, nearly half of the estimated 1 million tons of oil that makes its way into marine environments each year comes not from tanker spills but from land-based sources such as factories, farms, and cities. At sea, tanker spills account for about 10 percent of the oil in waters around the world, while regular operations of the shipping industry—through both legal and illegal discharges—contribute about one-third. Oil is also naturally released from under the ocean floor through fractures known as seeps.

    </p>
  </div>
  <div className="bg-gray-100 p-4 rounded-lg my-2 ">
    <h3 className="text-md font-bold text-gray-800 mb-2">article 5</h3>
    <p className="text-gray-700 ">

    Radioactive waste is any pollution that emits radiation beyond what is naturally released by the environment. It’s generated by uranium mining, nuclear power plants, and the production and testing of military weapons, as well as by universities and hospitals that use radioactive materials for research and medicine. Radioactive waste can persist in the environment for thousands of years, making disposal a major challenge. Consider the decommissioned Hanford nuclear weapons production site in Washington, where the cleanup of 56 million gallons of radioactive waste is expected to cost more than $100 billion and last through 2060. Accidentally released or improperly disposed of contaminants threaten groundwater, surface water, and marine resources.

    </p>
  </div>

</div>

<div className="bg-white  rounded-lg shadow-lg p-4 col-span-1 row-span-1 overflow-y-scroll">
  <div className="w-full  ">
    <h3 className="text-[35px] text-gray-900 font-bold mb-2">Complaints</h3>
    <div className="bg-gray-100 h-[200px] flex flex-col items-center justify-between p-4 rounded-lg my-2 ">
      <p>write a complaint</p>
     <textarea className='w-full' ></textarea>
     <button className="bg-blue-500 m-2 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-lg">Submit</button>

    </div>
  </div>
</div>

<div className="bg-white rounded-lg shadow-lg p-4 col-span-1 row-span-1 overflow-y-scroll">
  <h2 className="text-[35px] text-gray-900 font-bold mb-4">Updates</h2>
  <div className="w-full">
    <div className="bg-gray-100 p-4 rounded-lg my-2">
      <h3 className="text-md font-bold text-gray-800">Update 1</h3>
      <p className="text-gray-700">


      The ESR for 2020-21 also revealed that the G North ward (Dadar, Dharavi) had the highest amount of contamination in water samples at 3.4 per cent, followed by 2.4 per cent from P South (Goregaon), 2.3 per cent from T (Mulund), and 2.2 per cent from F North ward (Sion, Matunga).
      </p>

    </div>
    <div className="bg-gray-100 p-4 rounded-lg my-2">
      <h3 className="text-md font-bold text-gray-800">Update 2</h3>
      <p className="text-gray-700">


      Khadakwasla Constituency MLA Bhimrao Tapkir asked this question in the legislative session. It has been observed in the month of April that unprocessed domestic sewage and water-containing chemicals are being released into the reservoir of Khadakwasla Dam. Did the use of this contaminated water adversely affect the citizens, animals, plants and birds in the area or how? The question was raised by Tapkir.
      </p>

 

In reply, Chief Minister Shinde said that according to the report of the District Health Officer of the Zilla Parishad on August 8 and the report of the District Animal Husbandry Officer on August 13, this matter was not noticed.

    </div>
    <div className="bg-gray-100 p-4 rounded-lg my-2">
      <h3 className="text-md font-bold text-gray-800">Update 3</h3>
      <p className="text-gray-700">


      DJB’s plants can treat up to 1ppm of ammonia in raw water through chlorination, but using the chemical beyond this limit leads to the production of toxic compounds. Whenever ammonia levels breach the 1ppm mark, operations at water treatment plants are hit.
      </p>

A senior Delhi Jal Board (DJB) official said that to bring down the pollutant load on Tuesday, the water utility released water from the holding pond through the barrage to flush out the polluted water from the river. “We are also diluting the polluted water with clean raw water from Carrier Lined Canal (CLC) Munak. Haryana has also released fresh water from other tributaries such as the Somb to flush out the pollutants. We are hopeful that the polluted water will be cleared by Wednesday morning,” he said.

    </div>
  </div>
</div>

    </div>
  );
};

export default Contamination;
